export enum WeatherActionsType {
  GET_WEATHER_BY_CITY = 'GET_WEATHER_BY_CITY',
  GET_WEATHER_BY_CITY_SUCCESS = 'GET_WEATHER_BY_CITY_SUCCESS',
  // Error
  GET_WEATHER_BY_CITY_FAILURE = 'GET_WEATHER_BY_CITY_FAILURE'
}
