export enum AuthActionsType {
  SIGN_IN_USER = 'SIGN_IN_USER',
  SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS',
  LOG_IN_USER = 'LOG_IN_USER',
  LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS',
  // Error
  AUTH_ERROR = 'AUTH_ERROR'
}
